### ISSUE TITLE
[unplugin-turbo-console] Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by morpheux** [unplugin/unplugin-turbo-console#25]
### Describe the bug

During build receiving this error on 1.5.0

```
error during build:
TypeError: [unplugin-turbo-console] Cannot read properties of undefined (reading 'split')

    at Object.enter (file:///workspace/cloned-git-repository/node_modules/unplugin-turbo-console/dist/chunk-IXBC5KY4.js:220:62)
    at SyncWalker.visit (file:///workspace/cloned-git-repository/node_modules/ast-kit/dist/index.js:431:20)
    at SyncWalker.visit (file:///workspace/cloned-git-repository/node_modules/ast-kit/dist/index.js:467:18)
    at SyncWalker.visit (file:///workspace/cloned-git-repository/node_modules/ast-kit/dist/index.js:461:27)
    at SyncWalker.visit (file:///workspace/cloned-git-repository/node_modules/ast-kit/dist/index.js:467:18)
    at SyncWalker.visit (file:///workspace/cloned-git-repository/node_modules/ast-kit/dist/index.js:461:27)
    at SyncWalker.visit (file:///workspace/cloned-git-repository/node_modules/ast-kit/dist/index.js:467:18)
    at SyncWalker.visit (file:///workspace/cloned-git-repository/node_modules/ast-kit/dist/index.js:461:27)
    at SyncWalker.visit (file:///workspace/cloned-git-repository/node_modules/ast-kit/dist/index.js:461:27)
    at walk (file:///workspace/cloned-git-repository/node_modules/ast-kit/dist/index.js:605:19)
    at viteTransform (file:///workspace/cloned-git-repository/node_modules/unplugin-turbo-console/dist/chunk-IXBC5KY4.js:203:3)
    at transformer (file:///workspace/cloned-git-repository/node_modules/unplugin-turbo-console/dist/chunk-IXBC5KY4.js:328:12)
    at Object.transform (file:///workspace/cloned-git-repository/node_modules/unplugin-turbo-console/dist/chunk-IXBC5KY4.js:381:28)
    at plugin.transform (file:///workspace/cloned-git-repository/node_modules/unplugin/dist/index.mjs:1426:25)
    at file:///workspace/cloned-git-repository/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:19563:40
```

### Reproduction

Just build the code and error appears

### System Info

```Shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 11.79 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.4.0 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
  Browsers:
    Safari: 17.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yuyinws** [comment]
Thanks for your report. 
Had benn fixed on [v1.5.1](https://github.com/unplugin/unplugin-turbo-console/releases/tag/v1.5.1)
